name: Renumber objects and sprites

on: 
  # pull_request_review:
  pull_request:
    branches:
      - scripts_test
    # types: 
      # - submitted
    

jobs:
  renumber:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref }}
          # ref: ${{ github.head_ref }}
          fetch-depth: '0'
          
      - run: |
              echo "${{ toJson(github) }}"

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Object IDs calculation
        id: object_id_calculation
        run: |
              nextID=$( cat objects/nextObjectNumber.txt )
              maxID=$(ls -v objects/[0-9]* | tail -1 | sed 's/objects\///' | sed 's/.txt//')
              echo $nextID
              echo $maxID
              echo "nextID=$nextID" >> "$GITHUB_OUTPUT"
              echo "maxID=$maxID" >> "$GITHUB_OUTPUT"

      - if: steps.object_id_calculation.outputs.maxID > steps.object_id_calculation.outputs.nextID
        name: Renumbering objects
        run: |
              nextID=$( cat objects/nextObjectNumber.txt )
              maxID=$(ls -v objects/[0-9]* | tail -1 | sed 's/objects\///' | sed 's/.txt//')
              start_number=$maxID
              for fn in objects/[0-9]*.txt; do
                  id="${fn//[^0-9]/}"
                  (( id > nextID && id < start_number )) && start_number=$id
              done
              node RenumberObjects.js $start_number
              maxID=$(ls -v objects/[0-9]* | tail -1 | sed 's/objects\///' | sed 's/.txt//')
              echo -n $((maxID + 1)) > objects/nextObjectNumber.txt

      - if: steps.object_id_calculation.outputs.maxID > steps.object_id_calculation.outputs.nextID
        uses: EndBug/add-and-commit@v9
        with:
          message: "Renumber objects"
          default_author: github_actions
        